"""Tool-to-skill mapping and inference for OpenClaw chat."""

from __future__ import annotations

from typing import Any

_TOOL_TO_SKILL_MAP: dict[str, str] = {
    "qclaw_run_shell": "qclaw-run-shell",
    "qclaw_health_check": "qclaw-monitor-improver",
    "qclaw_list_teams": "qclaw-teams-hygiene",
    "qclaw_create_team": "qclaw-team-create",
    "qclaw_process_status": "qclaw-monitor-improver",
    "qclaw_read_log_tail": "qclaw-monitor-improver",
    "qclaw_monitor_snapshot": "qclaw-monitor-improver",
    "qclaw_monitor_update": "qclaw-chat-monitor-update",
    "qclaw_mcp_register": "qclaw-mcp-register",
    "qclaw_kanban_ide_handoff": "qclaw-chat-kanban-ide-handoff",
    "qclaw_get_errors": "qclaw-chat-errors",
    "qclaw_errors_to_cards": "qclaw-chat-errors",
    "qclaw_cards_get_errors": "qclaw-chat-errors",
    "qclaw_cards_errors_to_cards": "qclaw-chat-errors",
    "qclaw_cards_list_teams": "qclaw-chat-team-swarm",
    "qclaw_cards_get_cards": "qclaw-chat-team-swarm",
    "qclaw_cards_get_cards_todo": "qclaw-chat-team-swarm",
    "qclaw_cards_team_swarm_status": "qclaw-chat-team-swarm",
    "qclaw_cards_run_team_swarm": "qclaw-chat-team-swarm",
    "qclaw_cards_create_card": "qclaw-kanban-cards-create",
    "qclaw_cards_move_card": "qclaw-kanban-cards-maintain",
    "qclaw_team_kanban": "qclaw-chat-team-swarm",
    "qclaw_kanban_requirements": "qclaw-chat-requisitos",
    "qclaw_hermes_cron_health": "qclaw-hermes-cron-health",
    "qclaw_aws_overview": "qclaw-chat-aws-manage",
    "qclaw_aws_cost": "qclaw-chat-aws-manage",
    "qclaw_aws_ce_get_cost_and_usage": "qclaw-chat-aws-ce-get-cost-and-usage",
    "qclaw_aws_machines": "qclaw-chat-aws-manage",
    "qclaw_aws_waste": "qclaw-chat-aws-manage",
    "qclaw_aws_env": "qclaw-chat-aws-manage",
    "qclaw_team_files_search": "qclaw-chat-team-files-search",
    "qclaw_team_files_download": "qclaw-chat-team-files-download",
    "qclaw_team_files_send": "qclaw-chat-team-files-send",
    "qclaw_chat_widget_team_files": "qclaw-chat-team-files-dialog",
    "qclaw_team_rule_store": "qclaw-chat-team-rules",
    "qclaw_team_rule_list": "qclaw-chat-team-rules",
    "qclaw_team_rule_search": "qclaw-chat-team-rules",
    "qclaw_team_rule_delete": "qclaw-chat-team-rules",
    "qclaw_team_rules_summary": "qclaw-chat-team-rules",
    "qclaw_team_fact_store": "qclaw-chat-team-facts",
    "qclaw_team_fact_import": "qclaw-chat-team-facts",
    "qclaw_team_fact_list": "qclaw-chat-team-facts",
    "qclaw_team_fact_search": "qclaw-chat-team-facts",
    "qclaw_team_fact_delete": "qclaw-chat-team-facts",
    "qclaw_team_facts_summary": "qclaw-chat-team-facts",
    "qclaw_team_facts_for_roteiro": "qclaw-chat-team-facts",
    "qclaw_legal_pdf_extract": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_normas_list": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_norma_extract": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_evaluation_save": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_evaluation_get": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_evaluation_list": "qclaw-chat-avaliacao-juridica",
    "qclaw_legal_evaluation_search": "qclaw-chat-avaliacao-juridica",
    "qclaw_journal_rules_save": "qclaw-chat-revista-regras",
    "qclaw_journal_rules_get": "qclaw-chat-revista-regras",
    "qclaw_journal_rules_list": "qclaw-chat-revista-regras",
    "qclaw_journal_rules_search": "qclaw-chat-revista-regras",
    "qclaw_journal_rules_extract": "qclaw-chat-revista-regras",
    "qclaw_journal_rules_delete": "qclaw-chat-revista-regras",
    "qclaw_budget_get": "qclaw-chat-orcamento-domestico",
    "qclaw_budget_save": "qclaw-chat-orcamento-domestico",
    "qclaw_budget_summary": "qclaw-chat-orcamento-domestico",
    "qclaw_budget_analyze_csv": "qclaw-chat-orcamento-domestico",
    "qclaw_team_payment_save": "qclaw-chat-team-pagamentos",
    "qclaw_team_payment_get": "qclaw-chat-team-pagamentos",
    "qclaw_team_payment_list": "qclaw-chat-team-pagamentos",
    "qclaw_team_payment_search": "qclaw-chat-team-pagamentos",
    "qclaw_team_payment_delete": "qclaw-chat-team-pagamentos",
    "qclaw_team_payments_summary": "qclaw-chat-team-pagamentos",
    "qclaw_jobs_health": "qclaw-chat-jobs-health",
    "qclaw_token_mode": "qclaw-chat-consumo-modo",
    "qclaw_jobs_list_running": "qclaw-chat-jobs-manage",
    "qclaw_monitor_update": "qclaw-chat-monitor-update",
    "qclaw_mcp_register": "qclaw-mcp-register",
    "qclaw_kanban_ide_handoff": "qclaw-chat-kanban-ide-handoff",
    "qclaw_jobs_get_running": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cancel": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cancel_all_batches": "qclaw-chat-batch-kill-all",
    "qclaw_jobs_cron_list": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cron_get": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cron_action": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cron_create": "qclaw-chat-jobs-manage",
    "qclaw_jobs_cron_edit": "qclaw-chat-jobs-manage",
    "qclaw_list_chat_models": "qclaw-llm-models",
    "qclaw_model_quotas": "qclaw-llm-quotas",
    "qclaw_nano_banana_generate": "qclaw-nano-banana-pro",
    "qclaw_grok_imagine_generate": "qclaw-grok-imagine",
    "qclaw_imagen_generate": "qclaw-roteiro-gerar-imagem",
    "qclaw_openrouter_image_generate": "qclaw-image-models-catalog",
    "qclaw_show_media": "qclaw-chat-midia",
    "qclaw_show_slides_pdf": "qclaw-chat-slides-pdf",
    "qclaw_slides_corner_decor": "qclaw-slides-corner-decor",
    "qclaw_slides_replace_didactic": "qclaw-slides-replace-didactic",
    "qclaw_slides_batch_images": "qclaw-slides-batch-images",
    "qclaw_slides_narration": "qclaw-slides-narration",
    "qclaw_elevenlabs_narrate": "qclaw-elevenlabs-voice",
    "qclaw_gemini_music_generate": "qclaw-gemini-music",
    "qclaw_gemini_computer_use": "qclaw-gemini-computer-use",
    "qclaw_curso_notebooks_docker": "qclaw-curso-notebooks-docker",
    "qclaw_roteiro_book_generate": "qclaw-roteiro-livro-completo",
    "qclaw_roteiro_book_sync": "qclaw-roteiro-livro-sync",
    "qclaw_roteiro_course_sync": "qclaw-roteiro-curso-sync",
    "qclaw_roteiro_book_latex": "qclaw-roteiro-livro-latex",
    "qclaw_criar_projeto_livro": "qclaw-chat-book-generator",
    "qclaw_gerar_sumario": "qclaw-chat-book-generator",
    "qclaw_criar_outline_capitulo": "qclaw-chat-book-generator",
    "qclaw_escrever_secao": "qclaw-chat-book-generator",
    "qclaw_revisar_coesao": "qclaw-chat-book-generator",
    "qclaw_verificar_continuidade": "qclaw-chat-book-generator",
    "qclaw_humanizar_estilo": "qclaw-chat-book-generator",
    "qclaw_validar_referencias_abnt": "qclaw-chat-book-generator",
    "qclaw_exportar_markdown": "qclaw-chat-book-generator",
    "qclaw_exportar_docx": "qclaw-chat-book-generator",
    "qclaw_exportar_epub": "qclaw-chat-book-generator",
    "qclaw_exportar_pdf": "qclaw-chat-book-generator",
    "qclaw_listar_projetos": "qclaw-chat-book-generator",
    "qclaw_obter_projeto": "qclaw-chat-book-generator",
    "qclaw_roteiro_course_generate": "qclaw-roteiro-curso-completo",
    "qclaw_modulo_portal": "qclaw-modulo-portal",
    "qclaw_wacli_auth_qr": "qclaw-wacli-auth",
    "qclaw_wacli_unlock": "qclaw-wacli-unlock",
    "qclaw_whatsapp_status": "qclaw-chat-whatsapp-busca",
    "qclaw_send_whatsapp": "qclaw-wacli-auth",
    "qclaw_send_whatsapp_file": "qclaw-whatsapp-media-preview",
    "qclaw_team_whatsapp": "qclaw-team-whatsapp-associate",
    "qclaw_team_whatsapp_individual": "qclaw-team-whatsapp-individual",
    "qclaw_team_git": "qclaw-git-baseline",
    "qclaw_create_hermes_agent": "qclaw-hermes-cron-health",
    "qclaw_create_openai_swarm": "qclaw-swarm-topology",
    "qclaw_run_team_swarm": "qclaw-chat-team-swarm",
    "qclaw_run_swarm": "qclaw-chat-swarm-execute",
    "qclaw_swarm_list": "qclaw-chat-swarm-manage",
    "qclaw_swarm_get": "qclaw-chat-swarm-manage",
    "qclaw_swarm_create": "qclaw-chat-swarm-manage",
    "qclaw_swarm_update": "qclaw-chat-swarm-manage",
    "qclaw_swarm_delete": "qclaw-chat-swarm-manage",
    "qclaw_swarm_health": "qclaw-chat-swarm-manage",
    "qclaw_swarm_set_model": "qclaw-chat-swarm-manage",
    "qclaw_swarm_topology": "qclaw-chat-swarm-design",
    "qclaw_swarm_design": "qclaw-chat-swarm-design",
    "qclaw_evaluate_agents": "qclaw-agent-evaluate",
    "qclaw_fix_agents": "qclaw-agent-fix",
    "qclaw_create_kanban_card": "qclaw-kanban-cards-create",
    "qclaw_create_card_with_article": "qclaw-kanban-card-article-version",
    "qclaw_kanban_attach_upload": "qclaw-kanban-cards-attach-content",
    "qclaw_kanban_attach_move": "qclaw-kanban-cards-attach-content",
    "qclaw_kanban_attach_copy": "qclaw-kanban-cards-attach-content",
    "qclaw_kanban_list_attachments": "qclaw-kanban-cards-attach-content",
    "qclaw_kanban_attach_project_zip": "qclaw-kanban-cards-attach-content",
    "qclaw_kanban_attach_latex_zip": "qclaw-kanban-cards-attach-latex",
    "qclaw_desktop_screenshot": "qclaw-macos-desktop",
    "qclaw_desktop_click": "qclaw-macos-desktop",
    "qclaw_desktop_type": "qclaw-macos-desktop",
    "qclaw_desktop_key": "qclaw-macos-desktop",
    "qclaw_desktop_scroll": "qclaw-macos-desktop",
    "qclaw_desktop_list_windows": "qclaw-macos-desktop",
    "qclaw_desktop_open_app": "qclaw-macos-desktop",
    "qclaw_desktop_screen_info": "qclaw-macos-desktop",
    "qclaw_heygen_via_openclaw": "qclaw-heygen-mcp",
    "qclaw_suno_via_openclaw": "qclaw-suno-mcp",
    "qclaw_seedance_via_openclaw": "qclaw-seedance-video",
    "qclaw_virtual_band_create": "qclaw-chat-roteiro-musica",
    "qclaw_virtual_band_portrait": "qclaw-chat-roteiro-musica",
    "qclaw_virtual_band_job_status": "qclaw-chat-roteiro-musica",
    "qclaw_virtual_band_list_bands": "qclaw-chat-roteiro-musica",
    "qclaw_virtual_band_suggest_members": "qclaw-chat-roteiro-musica",
    "qclaw_rv_mongo_collections": "qclaw-chat-roteiro-mongo",
    "qclaw_rv_mongo_find": "qclaw-chat-roteiro-mongo",
    "qclaw_rv_mongo_count": "qclaw-chat-roteiro-mongo",
    "qclaw_rv_scripts_list": "qclaw-chat-roteiro-scripts",
    "qclaw_rv_scripts_get": "qclaw-chat-roteiro-scripts",
    "qclaw_rv_scripts_acts": "qclaw-chat-roteiro-scripts",
    "qclaw_rv_scripts_act": "qclaw-chat-roteiro-scripts",
    "qclaw_rv_scripts_insert": "qclaw-chat-roteiro-insert",
    "qclaw_rv_scripts_update": "qclaw-chat-roteiro-insert",
    "qclaw_rv_scripts_update_act": "qclaw-chat-roteiro-insert",
    "qclaw_rv_scripts_insert_acts": "qclaw-chat-roteiro-insert",
    "qclaw_rv_api_health": "qclaw-chat-roteiro-api",
    "qclaw_rv_api_get": "qclaw-chat-roteiro-api",
    "qclaw_rv_api_post": "qclaw-chat-roteiro-api",
    "qclaw_rv_api_patch": "qclaw-chat-roteiro-api",
    "qclaw_rv_api_delete": "qclaw-chat-roteiro-api",
    "qclaw_rv_job_status": "qclaw-chat-roteiro-api",
    "qclaw_rv_jobs_list": "qclaw-chat-roteiro-api",
    "qclaw_roteiro_book_cover_portrait": "qclaw-chat-roteiro-capas",
    "qclaw_book_cover_studio_brief": "qclaw-chat-book-cover-studio",
    "qclaw_book_cover_studio_concepts": "qclaw-chat-book-cover-studio",
    "qclaw_book_cover_studio_review": "qclaw-chat-book-cover-studio",
    "qclaw_book_cover_studio_export": "qclaw-chat-book-cover-studio",
    "qclaw_book_cover_studio_pipeline": "qclaw-chat-book-cover-studio",
    "qclaw_thumbnail_prompt": "qclaw-chat-roteiro-thumbnails",
    "qclaw_thumbnail_generate": "qclaw-chat-roteiro-thumbnails",
    "qclaw_thumbnail_concepts": "qclaw-chat-roteiro-thumbnails",
    "qclaw_thumbnail_job_status": "qclaw-chat-roteiro-thumbnails",
    "qclaw_chat_widget_visual_advanced": "qclaw-chat-roteiro-visual-avancado",
    "qclaw_chat_widget_storyboard_editor": "qclaw-chat-roteiro-storyboard",
    "qclaw_chat_widget_storyboard_image_editor": "qclaw-chat-roteiro-storyboard",
    "qclaw_chat_widget_comic_editor": "qclaw-chat-roteiro-hq-comics",
    "qclaw_chat_widget_character_editor": "qclaw-chat-roteiro-hq-comics",
    "qclaw_chat_widget_course_editor": "qclaw-chat-roteiro-cursos",
    "qclaw_chat_widget_course_manager": "qclaw-chat-roteiro-cursos",
    "qclaw_chat_widget_research_project_editor": "qclaw-chat-roteiro-pesquisa",
    "qclaw_chat_widget_research_ideas_editor": "qclaw-chat-roteiro-ideias-pesquisa",
    "qclaw_chat_widget_book_editor": "qclaw-chat-roteiro-livros",
    "qclaw_chat_widget_book_cover_editor": "qclaw-chat-book-cover-studio",
    "qclaw_chat_widget_book_objectives_editor": "qclaw-chat-roteiro-objetivos-livro",
    "qclaw_chat_widget_epub_preview": "qclaw-chat-epub-preview-dialog",
    "qclaw_chat_widget_book_chapter_preview": "qclaw-chat-epub-preview-dialog",
    "qclaw_chat_widget_epub_editor": "qclaw-chat-epub-preview-dialog",
    "qclaw_chapter_image_epub": "qclaw-chat-chapter-image-epub",
    "ask_qclaw_agent": "qclaw-claude-flow-mcp",
    "qclaw_save_project_note": "qclaw-kiro-dev",
    "qclaw_allowlist_list": "qclaw-team-whatsapp-group",
    "qclaw_allowlist_add": "qclaw-team-whatsapp-group",
    "qclaw_allowlist_remove": "qclaw-team-whatsapp-group",
    "qclaw_allowlist_toggle": "qclaw-team-whatsapp-group",
    "qclaw_wacli_group_numbers": "qclaw-wacli-group-numbers",
    "qclaw_whatsapp_groups_sync": "qclaw-wacli-groups-refresh",
    "qclaw_whatsapp_advanced_search": "whatsapp-advanced-search",
    "qclaw_whatsapp_search_crossgroup": "whatsapp-advanced-search",
    "qclaw_whatsapp_activity_ranking": "whatsapp-advanced-search",
    "qclaw_whatsapp_timeline": "whatsapp-advanced-search",
    "qclaw_whatsapp_person_summary": "whatsapp-advanced-search",
    "qclaw_team_context_search": "qclaw-team-context-search",
    "qclaw_team_articles": "qclaw-team-articles",
    "qclaw_article_images": "qclaw-chat-article-images",
    "qclaw_team_article_pdf": "qclaw-chat-team-article-pdf",
    "qclaw_index_team_articles": "qclaw-team-article-link",
    "qclaw_remove_team_articles": "qclaw-team-article-link",
    "web_search": "qclaw-mcp-search",
    "qclaw_email_memoria_index": "qclaw-chat-email-memoria",
    "qclaw_email_memoria_search": "qclaw-chat-email-memoria",
    "qclaw_email_memoria_list": "qclaw-chat-email-memoria",
    "qclaw_email_memoria_summary": "qclaw-chat-email-memoria",
    "qclaw_email_team_pdf_list": "qclaw-chat-email-team-pdf",
    "qclaw_email_team_pdf_save": "qclaw-chat-email-team-pdf",
    "qclaw_gmail_attachments_list": "qclaw-chat-gmail-attachments",
    "qclaw_gmail_attachments_download": "qclaw-chat-gmail-attachments",
    "qclaw_trello_connect": "qclaw-chat-trello",
    "qclaw_trello_boards": "qclaw-chat-trello",
    "qclaw_trello_board_detail": "qclaw-chat-trello",
    "qclaw_trello_card_create": "qclaw-chat-trello",
    "qclaw_trello_card_move": "qclaw-chat-trello",
    "qclaw_trello_kanban_sync": "qclaw-chat-trello-sync",
    "qclaw_trello_json_import": "qclaw-chat-trello-json-import",
    "qclaw_ai_kb_store": "qclaw-chat-ai-engineer",
    "qclaw_ai_kb_search": "qclaw-chat-ai-engineer",
    "qclaw_ai_kb_list": "qclaw-chat-ai-engineer",
    "qclaw_ai_kb_summary": "qclaw-chat-ai-engineer",
    "qclaw_ruflo_swarm_architecture": "qclaw-chat-ruflo-swarm",
    "qclaw_ruflo_swarm_audit": "qclaw-chat-ruflo-swarm",
    "qclaw_ruflo_swarm_validate": "qclaw-chat-ruflo-swarm",
    "qclaw_ruflo_swarm_plan": "qclaw-chat-ruflo-swarm",
    "qclaw_ruflo_swarm_scaffold": "qclaw-chat-ruflo-swarm",
    "qclaw_aula_store": "qclaw-chat-aulas-memoria",
    "qclaw_aula_search": "qclaw-chat-aulas-memoria",
    "qclaw_aula_list": "qclaw-chat-aulas-memoria",
    "qclaw_nota_store": "qclaw-chat-aulas-memoria",
    "qclaw_nota_search": "qclaw-chat-aulas-memoria",
    "qclaw_nota_list": "qclaw-chat-aulas-memoria",
    "qclaw_study_skill_store": "qclaw-chat-aulas-memoria",
    "qclaw_study_skill_search": "qclaw-chat-aulas-memoria",
    "qclaw_study_skill_list": "qclaw-chat-aulas-memoria",
    "qclaw_aulas_memoria_summary": "qclaw-chat-projeto-memoria",
    "qclaw_aulas_memoria_show": "qclaw-chat-projeto-memoria",
    "qclaw_memclaw_memoria_summary": "qclaw-chat-memclaw-memoria",
    "qclaw_memclaw_memoria_show": "qclaw-chat-memclaw-memoria",
    "qclaw_memclaw_memoria_search": "qclaw-chat-memclaw-memoria",
    "qclaw_whatsapp_memoria_index": "qclaw-chat-whatsapp-memoria",
    "qclaw_whatsapp_memoria_search": "qclaw-chat-whatsapp-memoria",
    "qclaw_whatsapp_memoria_list": "qclaw-chat-whatsapp-memoria",
    "qclaw_whatsapp_memoria_summary": "qclaw-chat-whatsapp-memoria",
    "qclaw_tool_learning_record": "qclaw-chat-autoaprimorar",
    "qclaw_tool_learning_search": "qclaw-chat-autoaprimorar",
    "qclaw_tool_learning_list": "qclaw-chat-autoaprimorar",
    "qclaw_tool_learning_stats": "qclaw-chat-autoaprimorar",
    "qclaw_chat_generation_status": "qclaw-slides-batch-images",
    "qclaw_slides_batch_artifacts": "qclaw-chat-slides-batch-artifacts",
    "qclaw_chat_failures": "qclaw-chat-falhas",
    "qclaw_chat_personality_get": "qclaw-chat-personalidade",
    "qclaw_chat_personality_samples": "qclaw-chat-personalidade",
    "qclaw_chat_personality_save": "qclaw-chat-personalidade",
    "qclaw_chat_personality_deactivate": "qclaw-chat-personalidade",
    "qclaw_chat_personality_summary": "qclaw-chat-personalidade",
    "qclaw_visual_memory_list": "qclaw-memoria-visual",
    "qclaw_visual_memory_get": "qclaw-memoria-visual",
    "qclaw_visual_memory_save": "qclaw-memoria-visual",
    "qclaw_visual_memory_add_photo": "qclaw-memoria-visual",
    "qclaw_visual_memory_remove_photo": "qclaw-memoria-visual",
    "qclaw_visual_memory_set_primary": "qclaw-memoria-visual",
    "qclaw_visual_memory_resolve": "qclaw-memoria-visual",
    "qclaw_visual_memory_deactivate": "qclaw-memoria-visual",
    "qclaw_visual_memory_summary": "qclaw-memoria-visual",
    "qclaw_visual_memory_merge_photos": "qclaw-memoria-visual",
    "qclaw_visual_memory_lora_train": "qclaw-memoria-visual",
    "qclaw_visual_memory_lora_status": "qclaw-memoria-visual",
    "qclaw_visual_memory_lora_evaluate": "qclaw-memoria-visual",
    "qclaw_character_search": "qclaw-personagem-preview",
    "qclaw_character_preview": "qclaw-personagem-preview",
    "qclaw_character_psych_save": "qclaw-personagem-psicologico",
    "qclaw_thumbnail_style_list": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_get": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_save": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_capture": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_resolve": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_deactivate": "qclaw-thumbnail-estilos",
    "qclaw_thumbnail_style_summary": "qclaw-thumbnail-estilos",
    "qclaw_user_data_get": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_save": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_delete_field": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_search": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_export": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_summary": "qclaw-chat-dados-pessoais",
    "qclaw_user_data_preview": "qclaw-chat-dados-pessoais",
    "qclaw_identidade_get": "qclaw-identidade-civil",
    "qclaw_identidade_save": "qclaw-identidade-civil",
    "qclaw_identidade_delete": "qclaw-identidade-civil",
    "qclaw_curriculum_list": "qclaw-curriculo",
    "qclaw_curriculum_register": "qclaw-curriculo",
    "qclaw_curriculum_extract": "qclaw-curriculo",
    "qclaw_curriculum_generate": "qclaw-curriculo",
    "qclaw_curriculum_send": "qclaw-curriculo",
    "qclaw_minicurriculum_generate": "qclaw-minicurriculo",
    "qclaw_minicurriculum_preview": "qclaw-minicurriculo",
    "qclaw_minicurriculum_send": "qclaw-minicurriculo",
    "qclaw_whatsapp_contacts_search": "qclaw-chat-whatsapp-busca",
    "qclaw_whatsapp_agenda_sync": "qclaw-chat-whatsapp-busca",
    "qclaw_whatsapp_agenda_list": "qclaw-chat-whatsapp-busca",
    "qclaw_whatsapp_agenda_stats": "qclaw-chat-whatsapp-busca",
    "qclaw_whatsapp_messages_search": "qclaw-chat-whatsapp-busca",
    "qclaw_gmail_send": "qclaw-gmail-imap",
    "qclaw_gmail_list": "qclaw-gmail-imap",
    "qclaw_gmail_read": "qclaw-gmail-imap",
    "qclaw_app_passwords_list": "qclaw-app-passwords",
    "qclaw_app_passwords_store": "qclaw-app-passwords",
    "qclaw_app_passwords_delete": "qclaw-app-passwords",
    "qclaw_google_oauth_list": "qclaw-google-oauth",
    "qclaw_google_oauth_status": "qclaw-google-oauth",
    "qclaw_google_oauth_upload": "qclaw-google-oauth",
    "qclaw_google_oauth_download": "qclaw-google-oauth",
    "qclaw_google_oauth_migrate": "qclaw-google-oauth",
    "qclaw_calendar_sync": "google-calendar-crud-sync",
    "qclaw_calendar_today": "google-calendar-crud-sync",
    "qclaw_calendar_week": "google-calendar-crud-sync",
    "qclaw_calendar_search": "google-calendar-crud-sync",
    "qclaw_calendar_create": "google-calendar-crud-sync",
    "qclaw_calendar_meet_create": "qclaw-calendar-meet",
    "qclaw_google_flights_search": "qclaw-google-flights",
    "qclaw_flights_search": "qclaw-flights-search",
    "qclaw_flights_providers_status": "qclaw-flights-search",
    "qclaw_roteiro_scene_setup": "qclaw-roteiro-montar-cena",
    "qclaw_youtube_metadata_generate": "qclaw-youtube-metadata",
    "qclaw_calendar_delete": "google-calendar-crud-sync",
    "qclaw_calendar_update": "google-calendar-crud-sync",
    "qclaw_calendar_status": "google-calendar-crud-sync",
    "qclaw_calendar_notion_sync": "notion-calendar-sync",
    "qclaw_calendar_notion_status": "notion-calendar-sync",
    "qclaw_calendar_notion_configure": "notion-calendar-sync",
    "qclaw_teams_calendar_sync": "teams-calendar-sync",
    "qclaw_teams_calendar_today": "teams-calendar-sync",
    "qclaw_teams_calendar_week": "teams-calendar-sync",
    "qclaw_teams_calendar_search": "teams-calendar-sync",
    "qclaw_teams_calendar_status": "teams-calendar-sync",
    "qclaw_notion_status": "qclaw-chat-notion",
    "qclaw_notion_configure": "qclaw-chat-notion",
    "qclaw_notion_search": "qclaw-chat-notion",
    "qclaw_notion_query": "qclaw-chat-notion",
    "qclaw_notion_get_page": "qclaw-chat-notion",
    "qclaw_notion_get_database": "qclaw-chat-notion",
    "qclaw_notion_create_row": "qclaw-chat-notion",
    "qclaw_notion_create_page": "qclaw-chat-notion",
    "qclaw_notion_update_page": "qclaw-chat-notion",
    "qclaw_overleaf_template_list": "qclaw-chat-latex-templates-search",
    "qclaw_overleaf_template_get": "qclaw-chat-latex-templates-search",
    "qclaw_overleaf_template_sync": "qclaw-chat-latex-templates-search",
    "qclaw_overleaf_template_extract": "qclaw-chat-latex-template-zip",
    "qclaw_overleaf_template_apply": "qclaw-chat-overleaf-template",
    "qclaw_overleaf_template_preview": "qclaw-chat-overleaf-template",
    "qclaw_overleaf_template_discover": "qclaw-chat-latex-template-pipeline",
    "qclaw_overleaf_template_fetch": "qclaw-chat-latex-template-pipeline",
    "qclaw_overleaf_template_catalog_search": "qclaw-chat-latex-template-pipeline",
    "qclaw_overleaf_template_catalog_get": "qclaw-chat-latex-template-pipeline",
    "qclaw_overleaf_template_catalog_sync": "qclaw-chat-latex-template-pipeline",
    "qclaw_overleaf_template_pipeline": "qclaw-chat-latex-template-pipeline",
    "qclaw_google_photos_picker_start": "qclaw-chat-google-fotos",
    "qclaw_google_photos_picker_poll": "qclaw-chat-google-fotos",
    "qclaw_google_photos_picker_list": "qclaw-chat-google-fotos",
    "qclaw_google_photos_sync": "qclaw-chat-google-fotos",
    "qclaw_google_photos_recent": "qclaw-chat-google-fotos",
    "qclaw_google_photos_get": "qclaw-chat-google-fotos",
    "qclaw_google_photos_status": "qclaw-chat-google-fotos",
    "qclaw_local_photos_search": "qclaw-chat-fotos-locais",
    "qclaw_local_photos_recent": "qclaw-chat-fotos-locais",
    "qclaw_local_photos_get": "qclaw-chat-fotos-locais",
    "qclaw_local_photos_roots": "qclaw-chat-fotos-locais",
    "qclaw_skills_list": "qclaw-mcp-skills-index",
    "qclaw_skills_get": "qclaw-mcp-skills-index",
    "qclaw_skills_search": "qclaw-mcp-skills-index",
    "qclaw_skills_run": "qclaw-mcp-skills-index",
    "qclaw_skills_tools_for_skill": "qclaw-mcp-skills-index",
    "qclaw_paper_orchestra_status": "qclaw-paper-orchestra",
    "qclaw_paper_orchestra_get": "qclaw-paper-orchestra",
    "qclaw_paper_orchestra_init": "qclaw-paper-orchestra",
    "qclaw_paper_orchestra_validate": "qclaw-paper-orchestra",
    "qclaw_paper_orchestra_build_pdf": "qclaw-paper-orchestra",
    "qclaw_paper_orchestra_run_script": "qclaw-paper-orchestra",
    "qclaw_article_references_verify": "qclaw-article-references-verify",
    "qclaw_crossref_get_doi": "qclaw-crossref-mcp",
    "qclaw_crossref_search_title": "qclaw-crossref-mcp",
    "qclaw_crossref_search_author": "qclaw-crossref-mcp",
    "qclaw_orcid_get_profile": "qclaw-orcid-mcp",
    "qclaw_orcid_search_researchers": "qclaw-orcid-mcp",
    "qclaw_orcid_resolve_researcher": "qclaw-orcid-mcp",
    "qclaw_orcid_get_works": "qclaw-orcid-mcp",
    "qclaw_orcid_get_work_detail": "qclaw-orcid-mcp",
    "qclaw_orcid_get_affiliations": "qclaw-orcid-mcp",
    "qclaw_comics_key_status": "qclaw-comics-mcp",
    "qclaw_comicvine_search": "qclaw-comics-mcp",
    "qclaw_comicvine_get": "qclaw-comics-mcp",
    "qclaw_anilist_search_media": "qclaw-comics-mcp",
    "qclaw_anilist_get_media": "qclaw-comics-mcp",
    "qclaw_anilist_search_character": "qclaw-comics-mcp",
    "qclaw_comics_list_layouts": "qclaw-comics-mcp",
    "qclaw_comics_build_page_layout": "qclaw-comics-mcp",
    "qclaw_comics_plan_saga_objective": "qclaw-comics-mcp",
    "qclaw_comics_plan_stories": "qclaw-comics-mcp",
    "qclaw_comics_plan_pages": "qclaw-comics-mcp",
    "qclaw_comics_plan_panels": "qclaw-comics-mcp",
    "qclaw_comics_generate_page_goals": "qclaw-comics-mcp",
    "qclaw_comics_generate_panel_goals": "qclaw-comics-mcp",
    "qclaw_character_vfx_key_status": "qclaw-character-vfx-mcp",
    "qclaw_character_vfx_list_layers": "qclaw-character-vfx-mcp",
    "qclaw_character_vfx_plan_pipeline": "qclaw-character-vfx-mcp",
    "qclaw_photo_to_video_list_providers": "qclaw-photo-to-video-mcp",
    "qclaw_photo_to_video_key_status": "qclaw-photo-to-video-mcp",
    "qclaw_photo_to_video_plan": "qclaw-photo-to-video-mcp",
    "qclaw_runway_via_openclaw": "qclaw-photo-to-video-mcp",
    "qclaw_social_stack_status": "qclaw-chat-social-stack-mcp",
    "qclaw_social_stack_list_layers": "qclaw-chat-social-stack-mcp",
    "qclaw_social_stack_key_status": "qclaw-chat-social-stack-mcp",
    "qclaw_social_stack_plan_pipeline": "qclaw-chat-social-stack-mcp",
    "qclaw_social_post_brief": "qclaw-chat-social-stack-mcp",
    "qclaw_social_calendar_build": "qclaw-chat-social-stack-mcp",
    "qclaw_social_stack_plan": "qclaw-chat-social-stack-mcp",
    "qclaw_software_planning_list_stages": "qclaw-chat-software-planning",
    "qclaw_software_planning_status": "qclaw-chat-software-planning",
    "qclaw_software_planning_key_status": "qclaw-chat-software-planning",
    "qclaw_software_planning_plan_pipeline": "qclaw-chat-software-planning",
    "qclaw_software_planning_prd_brief": "qclaw-chat-software-planning",
    "qclaw_software_planning_backlog_brief": "qclaw-chat-software-planning",
    "qclaw_software_planning_architecture_brief": "qclaw-chat-software-planning",
    "qclaw_software_planning_traceability_matrix": "qclaw-chat-software-planning",
    "qclaw_software_planning_plan": "qclaw-chat-software-planning",
    "qclaw_literature_search": "qclaw-roteiro-research",
    "qclaw_research_start": "qclaw-roteiro-research",
    "qclaw_humanize_text": "qclaw-text-humanizer-mcp",
    "qclaw_detect_ai_text": "qclaw-text-humanizer-mcp",
    "qclaw_humanizer_providers_status": "qclaw-text-humanizer-mcp",
    "qclaw_mcp__humantext__humanize_text": "qclaw-chat-humantext-mcp",
    "qclaw_mcp__humantext__humanize_and_detect": "qclaw-chat-humantext-mcp",
    "qclaw_mcp__humantext__detect_ai": "qclaw-chat-humantext-mcp",
    "qclaw_mcp__humantext__check_balance": "qclaw-chat-humantext-mcp",
    "qclaw_mcp__ai-humanizer__detect": "qclaw-chat-ai-humanizer-mcp",
}

_MCP_TOOL_SKILL_PREFIXES: tuple[tuple[str, str], ...] = (
    ("qclaw_mcp__humanizer-pro__", "qclaw-chat-humanizer-pro-mcp"),
    ("qclaw_mcp__memclaw__", "qclaw-chat-memclaw-memoria"),
)

_MCP_SKILL_ACCESS_TOOLS = frozenset(
    {
        "qclaw_skills_get",
        "qclaw_skills_run",
        "qclaw_skills_tools_for_skill",
    }
)


def extract_mcp_skill_from_tool_call(
    tool_name: str,
    args: dict[str, Any],
) -> str | None:
    """Return skill slug/name when a qclaw_skills_* tool accessed a specific skill."""
    if (tool_name or "").strip() not in _MCP_SKILL_ACCESS_TOOLS:
        return None
    if not isinstance(args, dict):
        return None
    name = str(args.get("name") or args.get("slug") or "").strip()
    return name or None


def _infer_skills_from_tools(
    tools_used: list[str],
    catalog_skills: list[dict[str, Any]],
) -> list[str]:
    """Infer skill names from tool calls when the LLM does not emit the tag.

    Uses a static mapping plus fuzzy matching against the skill catalog names.
    Returns deduplicated skill names preserving order of first occurrence.
    """
    if not tools_used:
        return []

    # Build a set of known skill names from the catalog for validation
    catalog_names = {
        (s.get("name") or "").strip().lower()
        for s in catalog_skills
        if s.get("name")
    }
    catalog_by_lower: dict[str, str] = {
        (s.get("name") or "").strip().lower(): (s.get("name") or "").strip()
        for s in catalog_skills
        if s.get("name")
    }

    inferred: list[str] = []
    seen: set[str] = set()

    for tool in tools_used:
        tool_name = (tool or "").strip()
        if not tool_name:
            continue

        # Try static mapping first
        mapped = _TOOL_TO_SKILL_MAP.get(tool_name)
        if mapped:
            key = mapped.lower()
            # If catalog has the skill, use the canonical name from catalog
            canonical = catalog_by_lower.get(key, mapped)
            if key not in seen:
                seen.add(key)
                inferred.append(canonical)
            continue

        prefix_mapped: str | None = None
        for prefix, skill_slug in _MCP_TOOL_SKILL_PREFIXES:
            if tool_name.startswith(prefix):
                prefix_mapped = skill_slug
                break
        if prefix_mapped:
            key = prefix_mapped.lower()
            canonical = catalog_by_lower.get(key, prefix_mapped)
            if key not in seen:
                seen.add(key)
                inferred.append(canonical)
            continue

        # Fuzzy: if tool name contains a catalog skill slug, match it
        tool_lower = tool_name.lower().replace("_", "-")
        for cat_lower, cat_name in catalog_by_lower.items():
            if cat_lower in tool_lower or tool_lower in cat_lower:
                if cat_lower not in seen:
                    seen.add(cat_lower)
                    inferred.append(cat_name)
                break

    return inferred
