#!/usr/bin/env bash
# Initialize (or reset) a clean git repo in gois-lite with a single commit dated today.
#
# Usage:
#   ./scripts/lib/init_gois_lite_git.sh [/Volumes/NAUBER/gois-lite]

set -euo pipefail

TARGET="${1:-${GOIS_LITE_TARGET:-/Volumes/NAUBER/gois-lite}}"

if [[ ! -d "$TARGET" ]]; then
  echo "gois-lite target missing: $TARGET" >&2
  exit 1
fi

cd "$TARGET"

# Remove git metadata copied from main gois and local cruft.
rm -rf .git .github
rm -f .gitmodules config.yaml.bak .env.bak .env.bak.* 2>/dev/null || true
find . -name '.DS_Store' -delete 2>/dev/null || true
find . -maxdepth 3 -name '*.bak' -delete 2>/dev/null || true

cat > .gitignore <<'EOF'
# secrets / runtime
.env
.env.*
!.env.example
.stack/
.venv/
hermes/logs/
*.log
*.log.*

# python / tooling
__pycache__/
*.py[cod]
.pytest_cache/
.ruff_cache/
.mypy_cache/
*.egg-info/

# os / editor
.DS_Store
.idea/
.vscode/

# local data
tmp/
var/
output/
*.db
*.jpeg
*.jpg
*.png
ruvector.db
agentdb.rvf.lock
EOF

if [[ -d .git ]]; then
  rm -rf .git
fi

git init -b main >/dev/null

# Single snapshot commit — author and committer date = now (today).
GIT_ISO="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
export GIT_AUTHOR_DATE="$GIT_ISO"
export GIT_COMMITTER_DATE="$GIT_ISO"

git add -A
if git diff --cached --quiet; then
  echo "nothing to commit in $TARGET"
  exit 0
fi

git commit -m "$(cat <<EOF
gois-lite: snapshot Chat + Kanban + MCP IDE

Clean deployment tree without OpenClaw/QClaw. Generated by init_gois_lite_git.sh.
EOF
)"

echo "git ok: $(git rev-parse --short HEAD) @ $GIT_ISO"
git log -1 --format='  %h %ad %s' --date=iso-strict
git status -sb

GITHUB_REMOTE="${GOIS_LITE_GITHUB_REMOTE:-https://github.com/naubergois/gois-lite.git}"
if [[ "${GOIS_LITE_GITHUB_PUSH:-0}" == "1" ]]; then
  git remote remove origin 2>/dev/null || true
  git remote add origin "$GITHUB_REMOTE"
  echo "→ push $GITHUB_REMOTE (main, force — snapshot único)"
  git push -u origin main --force
  echo "github ok: $GITHUB_REMOTE @ $(git rev-parse --short HEAD)"
fi
